kube_version: v1.29.5
cluster_name: cluster.local
container_manager: containerd
system_upgrade_reboot: on-upgrade

etcd_deployment_type: host
etcd_retries: 10

kube_network_plugin: calico
calico_ipip_mode: Never
calico_vxlan_mode: Always
calico_network_backend: vxlan
calico_apiserver_enabled: true

kube_proxy_mode: ipvs
kube_service_addresses: 10.233.0.0/18
kube_pods_subnet: 10.233.64.0/18
kube_network_node_prefix: 24
kubelet_max_pods: 110

dns_mode: coredns
enable_nodelocaldns: true
resolvconf_mode: host_resolvconf
kube_resolv_conf: "/etc/resolv.conf"
nameservers: ["192.168.1.69"]

### Hardening ###
kubernetes_audit: true
audit_log_maxage: 30
audit_log_maxbackups: 10
audit_log_maxsize: 100
kube_apiserver_request_timeout: 120s
kube_controller_manager_bind_address: 127.0.0.1 
kube_controller_terminated_pod_gc_threshold: 50

kube_scheduler_bind_address: 127.0.0.1

kube_apiserver_enable_admission_plugins:
  - AlwaysPullImages                            
  - NodeRestriction                             

kubelet_event_record_qps: 1
tls_cipher_suites:
  - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305

kube_encrypt_secret_data: true
kube_encryption_resources: [secrets]
kube_encryption_algorithm: secretbox
